### ISSUE TITLE
Errors and Bugs

### ISSUE THREAD

**Issue by mistik911** [NekoNova/WatcherEx#2]
I get this when I try to set the Action Set under filters and watcher crashs. 

...dStar\Addons\WatcherEx\GeminiFilter\GeminiFilter.lua:269: attempt to index field 'tAbility' (a nil value)
stack trace:
	...dStar\Addons\WatcherEx\GeminiFilter\GeminiFilter.lua:269: in function 'IsPassed'
	...dStar\Addons\WatcherEx\GeminiFilter\GeminiFilter.lua:1758: in function 'IsPassed'
	...dStar\Addons\WatcherEx\GeminiFilter\GeminiFilter.lua:1785: in function 'Update'
	...aming\NCSOFT\WildStar\Addons\WatcherEx\WatcherEx.lua:159: in function <...aming\NCSOFT\WildStar\Addons\WatcherEx\WatcherEx.lua:140>

I also get this error when I try to set the MP (Focus) under filters and watcher crashs.

...r\Addons\WatcherEx\GeminiSettings\GeminiSettings.lua:33: bad argument #1 to 'pairs' (table expected, got nil)
stack trace:
	[C]: in function 'pairs'
	...r\Addons\WatcherEx\GeminiSettings\GeminiSettings.lua:33: in function 'DeepMerge'
	...r\Addons\WatcherEx\GeminiSettings\GeminiSettings.lua:66: in function 'LoadSettings'
	...dStar\Addons\WatcherEx\GeminiFilter\GeminiFilter.lua:725: in function 'create'
	...dStar\Addons\WatcherEx\GeminiFilter\GeminiFilter.lua:1525: in function 'AddFilter'
	...aming\NCSOFT\WildStar\Addons\WatcherEx\WatcherEx.lua:322: in function <...aming\NCSOFT\WildStar\Addons\WatcherEx\WatcherEx.lua:321>

You can also not select the icon overlay under Ability Icon Options under Notifications and you can not set the font or any sounds.

Thanks for keeping this up to date, sry it's been such a pain for you to fix.

**Comment by mistik911** [comment]
Also for whatever reason raretracker shows up under the esc menu even though I don't have it installed. I uninstalled watcherex and it removes raretracker from the esc menu.

**Comment by NekoNova** [comment]
will look into it.
The Raretracker mention sounds odd.

**Comment by NekoNova** [comment]
Can you please open separate issues for the:
* Raretracker reference
* Icon Overlay
* Icon Font
* Icon sound.
Easier to track issues then for me
